export enum Routes {
  AUTH = 'auth',
  USERS = 'users',
  ROLE = 'role',
  CONTACT = 'contact',
  RELY = 'rely',
  NEWPOST = 'posts',
  NEWSCATEGORY = 'newscategory',
  EVENT = 'event',
  ORGANIZE = 'organize-membership-title',
  BUSINESSAREAS = 'business-areas',
  MEMBER = 'member',
  COMMENT = 'comment',
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  ROLE = 'ROLE_SERVICE',
  CONTACT = 'CONTACT_SERVICE',
  RELY = 'RELY_SERVICE',
  NEWPOST = 'NEWPOST_SERVICE',
  MAILER = 'MAILER_SERVICE',
  NEWSCATEGORY = 'NEWSCATEGORY_SERVICE',
  EVENT = 'EVENT_SERVICE',
  ORGANIZE = 'ORGANIZEMEMBERSHIPTITLE_SERVICE',
  BUSINESSAREAS = 'BUSINESS-AREAS',
  MEMBER = 'MEMBER_SERVICE',
  COMMENT = 'COMMENT_SERVICE',
}
